routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'HomeController@index');

//Booking routes
Route::get('/booking', 'BookingController@index');
Route::post('/booking', 'BookingController@store');
Route::get('/booking/success', 'BookingController@success');
Route::get('/booking/failure', 'BookingController@failure');

//Admin routes
Route::group(['prefix' => 'admin'], function () {

    //Auth::routes();
    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'Auth\RegisterController@register');
    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    //Admin secure routes
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', 'AdminController@index');

        Route::resource('customer', 'Admin\CustomerController');
        Route::resource('city', 'Admin\CityController');
        Route::resource('booking', 'Admin\BookingController');
        Route::resource('cleaner', 'Admin\CleanerController');
    });
});

app/City.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class City extends Model {

    //public $timestamps = false;
    protected $fillable = ['name'];

    public function cleaners() {
        return $this->belongsToMany(Cleaner::class);
    }

    public function customers() {
        return $this->hasMany(Customer::class);
    }

    public function bookings() {
        return $this->hasMany(Booking::class);
    }

}

app/Http/Controllers/Admin/CityController.php
<?php

namespace App\Http\Controllers\Admin;

use App\City;
use App\Cleaner;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCityRequest;

class CityController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $cities = City::paginate(env('PAGINATION_ONPAGE', 10));
        return view('admin.city.index', compact('cities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('admin.city.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCityRequest $request) {
        City::create(request(['name']));
        session()->flash('message-success', 'City was stored');
        return redirect()->route('city.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function show(City $city) {
        $cleaners = Cleaner::with('cities')->whereHas('cities', function($q) use ($city) {
                    $q->where('id', $city->id);
                })->paginate(env('PAGINATION_ONPAGE', 10));
        return view('admin.city.show', compact('city', 'cleaners'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function edit(City $city) {
        return view('admin.city.edit', compact('city'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCityRequest $request, City $city) {
        $city->name = request('name');
        $city->save();
        session()->flash('message-success', 'City was updated');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\City  $city
     * @return \Illuminate\Http\Response
     */
    public function destroy(City $city) {
        try {
            $city->delete();
            session()->flash('message-success', 'City was removed');
        } catch (\Exception $e) {
            redirect()->route('city.index')->with('message-failure', 'You can not delete a city that has bookings or cleaners.');
        }
        return redirect()->route('city.index');
    }

}

resources/views/admin/city/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">City add</div>
                <div class="panel-body">
                    <form action="{{ route('city.store') }}" method="POST" id="a_city">
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="City" value="{{old('name')}}" required>
                            @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-default">Add</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/city/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">City edit</div>
                <div class="panel-body">
                    <form action="{{ route('city.update', ['id' => $city->id]) }}" method="POST" id="a_city">
                        {{ method_field('PUT') }}
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name">Name</label>
                            <input type="text" class="form-control" name="name" id="name" placeholder="City" value="{{ $city->name }}" required>
                            @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-default">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/city/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">City list</div>
                <div class="panel-body">
                    @if ($cities->isNotEmpty())
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th></th>
                            </tr>
                        </thead>
                        @foreach($cities as $city)
                        <tr>
                            <td>
                                <a href="{{ route('city.show', ['id' => $city->id]) }}">{{ $city->name }}</a>
                            </td>
                            <td class="text-right">
                                <form action="{{ route('city.destroy', ['id' => $city->id]) }}" method="POST">
                                    <div class="btn-group-xs" role="group" aria-label="...">
                                        <a href="{{ route('city.edit', ['id' => $city->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-danger">
                                            <span class="glyphicon glyphicon-trash"></span> Remove
                                        </button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </table>
                    @else
                    <div class="alert alert-danger" role="alert">No cities defined</div>
                    @endif
                    <div class="text-center">
                        <a class="btn btn-default" href="{{ route('city.create') }}">Add city</a>
                    </div>
                    <div class="text-center">{{ $cities->links() }}</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/city/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">City</div>
                <div class="panel-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            <div class="row">
                                <div class="col-md-8">
                                    {{ $city->name }}
                                </div>
                                <div class="col-md-4 text-right">
                                    <form action="{{ route('city.destroy', ['id' => $city->id]) }}" method="POST">
                                        <div class="btn-group-xs" role="group" aria-label="...">
                                            <a href="{{ route('city.edit', ['id' => $city->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-danger">
                                                <span class="glyphicon glyphicon-trash"></span> Remove
                                            </button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </li>
                    </ul>
                    @if ($cleaners->isNotEmpty())
                    <p><strong>Cleaners</strong></p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td>Cleaner name</td>
                                <td>Quality score</td>
                                <td></td>
                            </tr>
                        </thead>
                        @foreach ($cleaners as $cleaner)
                        <tr>
                            <td><a href="{{ route('cleaner.show', ['id' => $cleaner->id]) }}">{{ $cleaner->first_name }} {{ $cleaner->last_name }}</a></td>
                            <td>{{ $cleaner->quality_score }}</td>
                            <td class="text-right">
                                <form action="{{ route('cleaner.destroy', ['id' => $cleaner->id]) }}" method="POST">
                                    <div class="btn-group-xs" role="group" aria-label="...">
                                        <a href="{{ route('cleaner.edit', ['id' => $cleaner->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-danger">
                                            <span class="glyphicon glyphicon-trash"></span> Remove
                                        </button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </table>
                    <div class="text-center">{{ $cleaners->links() }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection