routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'HomeController@index');

//Booking routes
Route::get('/booking', 'BookingController@index');
Route::post('/booking', 'BookingController@store');
Route::get('/booking/success', 'BookingController@success');
Route::get('/booking/failure', 'BookingController@failure');

//Admin routes
Route::group(['prefix' => 'admin'], function () {

    //Auth::routes();
    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'Auth\RegisterController@register');
    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    //Admin secure routes
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', 'AdminController@index');

        Route::resource('customer', 'Admin\CustomerController');
        Route::resource('city', 'Admin\CityController');
        Route::resource('booking', 'Admin\BookingController');
        Route::resource('cleaner', 'Admin\CleanerController');
    });
});

app/Cleaner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cleaner extends Model {

    protected $fillable = ['first_name', 'last_name', 'quality_score', 'email'];

    public function cities() {
        return $this->belongsToMany(City::class);
    }

    public function bookings() {
        return $this->hasMany(Booking::class);
    }

}

app/Http/Controllers/Admin/CleanerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Booking;
use App\Cleaner;
use App\City;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreCleanerRequest;

class CleanerController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $cleaners = Cleaner::with('cities')->paginate(env('PAGINATION_ONPAGE', 10));
        return view('admin.cleaner.index', compact('cleaners'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Cleaner $cleaner) {
        $cities = City::all();
        return view('admin.cleaner.create', compact('cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCleanerRequest $request) {
        $cleaner = Cleaner::create(request(['first_name', 'last_name', 'quality_score', 'email']));
        $cleaner->cities()->attach(request('city_id'));
        session()->flash('message-success', 'Cleaner was stored');
        return redirect()->route('cleaner.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cleaner  $cleaner
     * @return \Illuminate\Http\Response
     */
    public function show(Cleaner $cleaner) {
        $bookings = Booking::with('customer', 'cleaner', 'city')->where('cleaner_id', $cleaner->id)->paginate(env('PAGINATION_ONPAGE', 10));
        return view('admin.cleaner.show', compact('cleaner', 'bookings'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cleaner  $cleaner
     * @return \Illuminate\Http\Response
     */
    public function edit(Cleaner $cleaner) {
        $citiesChecked = [];
        foreach ($cleaner->cities as $city) {
            $citiesChecked[] = $city->id;
        }
        $citiesList = City::all();
        return view('admin.cleaner.edit', compact('cleaner', 'citiesChecked', 'citiesList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cleaner  $cleaner
     * @return \Illuminate\Http\Response
     */
    public function update(StoreCleanerRequest $request, Cleaner $cleaner) {
        $cleaner->update(request(['first_name', 'last_name', 'quality_score', 'email']));
        $cleaner->cities()->sync(request('city_id'), true);
        session()->flash('message-success', 'Cleaner was updated');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cleaner  $cleaner
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cleaner $cleaner) {
        try {
            $cleaner->delete();
            $cleaner->cities()->detach();
            session()->flash('message-success', 'Cleaner was removed');
        } catch (\Exception $e) {
            redirect()->route('cleaner.index')->with('message-failure', 'You can not delete a cleaner that has bookings.');
        }
        return redirect()->route('cleaner.index');
    }

}

resources/views/admin/cleaner/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Cleaner add</div>
                <div class="panel-body">
                    <form action="{{ route('cleaner.store') }}" method="POST" id="a_cleaner">
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
                            <label for="first_name">First name</label>
                            <input type="text" class="form-control" name="first_name" id="first_name" placeholder="First name" value="{{old('first_name')}}" required>
                            @if ($errors->has('first_name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('first_name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
                            <label for="last_name">Last name</label>
                            <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Last name" value="{{old('last_name')}}" required>
                            @if ($errors->has('last_name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('last_name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email">E-mail</label>
                            <input type="text" class="form-control" name="email" id="email" placeholder="E-mail" value="{{old('email')}}" required>
                            @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('quality_score') ? ' has-error' : '' }}">
                            <label for="quality_score">Quality score</label>
                            <input type="number" step="0.1" class="form-control" name="quality_score" id="quality_score" placeholder="5.0" value="{{old('quality_score')}}" required>
                            @if ($errors->has('quality_score'))
                            <span class="help-block">
                                <strong>{{ $errors->first('quality_score') }}</strong>
                            </span>
                            @endif
                        </div>
                        <hr>
                        <strong>Cities</strong>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-2"></div>
                                <?php
                                $count = 1;
                                $maxCount = count($cities);
                                ?>
                                @foreach($cities as $city)
                                <div class="col-md-3">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" name="city_id[]" value="{{ $city->id }}"> {{ $city->name }}
                                    </label>
                                </div>
                                @if($count % 3 == 0)
                            </div>
                            <div class="row">
                                <div class="col-md-2"></div>
                                @endif
                                <?php $count++ ?>
                                @endforeach
                            </div>
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-default">Add</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/cleaner/edit.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Cleaner edit</div>
                <div class="panel-body">
                    <form action="{{ route('cleaner.update', ['id' => $cleaner->id]) }}" method="POST" id="a_cleaner">
                        {{ method_field('PUT') }}
                        {{ csrf_field() }}
                        <div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
                            <label for="first_name">First name</label>
                            <input type="text" class="form-control" name="first_name" id="first_name" placeholder="First name" value="{{$cleaner->first_name}}" required>
                            @if ($errors->has('first_name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('first_name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
                            <label for="last_name">Last name</label>
                            <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Last name" value="{{$cleaner->last_name}}" required>
                            @if ($errors->has('last_name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('last_name') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email">E-mail</label>
                            <input type="text" class="form-control" name="email" id="email" placeholder="E-mail" value="{{$cleaner->email}}" required>
                            @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                            @endif
                        </div>
                        <div class="form-group{{ $errors->has('quality_score') ? ' has-error' : '' }}">
                            <label for="quality_score">Quality score</label>
                            <input type="text" class="form-control" name="quality_score" id="quality_score" placeholder="5.0" value="{{$cleaner->quality_score}}" required>
                            @if ($errors->has('quality_score'))
                            <span class="help-block">
                                <strong>{{ $errors->first('quality_score') }}</strong>
                            </span>
                            @endif
                        </div>
                        <hr>
                        <strong>Cities</strong>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-2"></div>
                                <?php
                                $count = 1;
                                $maxCount = count($citiesList);
                                ?>
                                @foreach($citiesList as $city)
                                <div class="col-md-3">
                                    <label class="checkbox-inline">
                                        <input type="checkbox" name="city_id[]" value="{{ $city->id }}"{{ (in_array($city->id, $citiesChecked)) ? ' checked' : '' }}> {{ $city->name }}
                                    </label>
                                </div>
                                @if($count % 3 == 0)
                            </div>
                            <div class="row">
                                <div class="col-md-2"></div>
                                @endif
                                <?php $count++ ?>
                                @endforeach
                            </div>
                        </div>
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-default">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection

resources/views/admin/cleaner/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Cleaners</div>
                <div class="panel-body">
                    @if ($cleaners->isNotEmpty())
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>E-mail</th>
                                <th>Quality score</th>
                                <th></th>
                            </tr>
                        </thead>
                        @foreach($cleaners as $cleaner)
                        <tr>
                            <td><a href="{{ route('cleaner.show', ['id' => $cleaner->id]) }}">{{ $cleaner->first_name }} {{ $cleaner->last_name }}</a></td>
                            <td>{{ $cleaner->email }}</td>
                            <td>{{ $cleaner->quality_score }}</td>
                            <td class="text-right">
                                <form action="{{ route('cleaner.destroy', ['id' => $cleaner->id]) }}" method="POST">
                                    <div class="btn-group-xs" role="group" aria-label="...">
                                        <a href="{{ route('cleaner.edit', ['id' => $cleaner->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-danger">
                                            <span class="glyphicon glyphicon-trash"></span> Remove
                                        </button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </table>
                    @else
                    <div class="alert alert-danger" role="alert">No cleaners defined</div>
                    @endif
                    <div class="text-center">
                        <a class="btn btn-default" href="{{ route('cleaner.create') }}">Add cleaner</a>
                    </div>
                    <div class="text-center">{{ $cleaners->links() }}</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/cleaner/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Cleaner</div>
                <div class="panel-body">
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>First name:</strong>
                        </div>
                        <div class="col-md-6">
                            {{ $cleaner->first_name }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>Last name:</strong>
                        </div>
                        <div class="col-md-6">
                            {{ $cleaner->last_name }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>E-mail:</strong>
                        </div>
                        <div class="col-md-6">
                            {{ $cleaner->email }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>Quality score:</strong>
                        </div>
                        <div class="col-md-6">
                            {{ $cleaner->quality_score }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>Cities:</strong>
                        </div>
                        <div class="col-md-6">
                            <ul>
                                @foreach ($cleaner->cities as $city)
                                <li>{{$city->name}}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                    <div class="form-group text-center">
                        <form action="{{ route('cleaner.destroy', ['id' => $cleaner->id]) }}" method="POST">
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="{{ route('cleaner.edit', ['id' => $cleaner->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"></span> Remove
                                </button>
                            </div>
                        </form>
                    </div>
                    @if ($bookings->isNotEmpty())
                    <p><strong>Bookings</strong></p>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <td>ID</td>
                                <td>Customer name</td>
                                <td>Customer phone</td>
                                <td>Customer e-mail</td>
                                <td>City</td>
                                <td>Booking start</td>
                                <td>Booking end</td>
                                <td></td>
                            </tr>
                        </thead>
                        @foreach ($bookings as $booking)
                        <tr>
                            <td><a href="{{ route('booking.show', ['booking' => $booking->id]) }}">{{ $booking->id }}</a></td>
                            <td><a href="{{ route('customer.show', ['id' => $booking->customer->id]) }}">{{ $booking->customer->first_name }} {{ $booking->customer->last_name }}</a></td>
                            <td>{{ $booking->customer->phone }}</td>
                            <td>{{ $booking->customer->email }}</td>
                            <td><a href="{{ route('city.show', ['id' => $booking->city->id]) }}">{{ $booking->city->name }}</a></td>
                            <td>{{ $booking->date_from }}</td>
                            <td>{{ $booking->date_to }}</td>
                            <td class="text-right">
                                <form action="{{ route('booking.destroy', ['id' => $booking->id]) }}" method="POST">
                                    <div class="btn-group-xs" role="group" aria-label="...">
                                        <a href="{{ route('booking.edit', ['id' => $booking->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-danger">
                                            <span class="glyphicon glyphicon-trash"></span> Remove
                                        </button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </table>
                    <div class="text-center">{{ $bookings->links() }}</div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection