routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'HomeController@index');

//Booking routes
Route::get('/booking', 'BookingController@index');
Route::post('/booking', 'BookingController@store');
Route::get('/booking/success', 'BookingController@success');
Route::get('/booking/failure', 'BookingController@failure');

//Admin routes
Route::group(['prefix' => 'admin'], function () {

    //Auth::routes();
    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'Auth\RegisterController@register');
    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    //Admin secure routes
    Route::group(['middleware' => ['auth']], function () {
        Route::get('/', 'AdminController@index');

        Route::resource('customer', 'Admin\CustomerController');
        Route::resource('city', 'Admin\CityController');
        Route::resource('booking', 'Admin\BookingController');
        Route::resource('cleaner', 'Admin\CleanerController');
    });
});

app/Booking.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Booking extends Model {

    protected $fillable = [
        'customer_id',
        'cleaner_id',
        'city_id',
        'date_from',
        'date_to'
    ];

    public function customer() {
        return $this->belongsTo(Customer::class);
    }

    public function cleaner() {
        return $this->belongsTo(Cleaner::class);
    }

    public function city() {
        return $this->belongsTo(City::class);
    }

    public function getBookedCleaners($fromDate, $toDate) {
        return DB::table('bookings')->
                        select('cleaner_id')->
                        //Cleaner can not be in 2+ cities in same time
                        //where('city_id', '=', $city)->
                        where(
                                function($q) use($fromDate, $toDate) {
                            $q->where([
                                ['date_from', '>=', $fromDate],
                                ['date_to', '<=', $toDate]
                            ])->orWhere([
                                ['date_from', '<', $fromDate],
                                ['date_to', '>', $fromDate]
                            ])->orWhere([
                                ['date_from', '<', $toDate],
                                ['date_to', '>', $toDate]
                            ])->orWhere([
                                ['date_from', '<', $fromDate],
                                ['date_to', '>', $toDate]
                            ]);
                        })->get();
    }

    public function getFreeCleaners($fromDate, $toDate, $city, $onlyOne = true) {
        $cleaners = $this->getBookedCleaners($fromDate, $toDate);
        $cleaners = $cleaners->map(function($x) {
                    return (array) $x;
                })->toArray();
        if (empty($cleaners)) {
            if ($onlyOne) {
                return City::find($city)->cleaners()->orderBy('cleaners.quality_score', 'DESC')->first();
            } else {
                return City::find($city)->cleaners()->orderBy('cleaners.quality_score', 'DESC');
            }
            //return City::find($city)->cleaners()->whereNotIn('city_cleaner.cleaner_id', $cleaners)->orderBy('quality_score', 'DESC')->first();
        } else {
            if ($onlyOne) {
                return City::find($city)->cleaners()->whereNotIn('city_cleaner.cleaner_id', $cleaners)->orderBy('quality_score', 'DESC')->first();
            } else {
                return City::find($city)->cleaners()->whereNotIn('city_cleaner.cleaner_id', $cleaners)->orderBy('quality_score', 'DESC');
            }
        }
    }

    public function getCleanerBookings($fromDate, $toDate, $cleanerId) {
        return DB::table('bookings')->
                select('cleaner_id')->
                //Cleaner can not be in 2+ cities in same time
                //where('city_id', '=', $city)->
                where('cleaner_id', $cleanerId)->
                where('id', '<>', $this->id)->
                where(
                        function($q) use($fromDate, $toDate) {
                    $q->where([
                        ['date_from', '>=', $fromDate],
                        ['date_to', '<=', $toDate]
                    ])->orWhere([
                        ['date_from', '<', $fromDate],
                        ['date_to', '>', $fromDate]
                    ])->orWhere([
                        ['date_from', '<', $toDate],
                        ['date_to', '>', $toDate]
                    ])->orWhere([
                        ['date_from', '<', $fromDate],
                        ['date_to', '>', $toDate]
                    ]);
                })->get();
    }

}

app/Http/Controllers/Admin/BookingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Booking;
use App\City;
use App\Customer;
use App\Cleaner;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Mail\CustomerBookingInfo;
use App\Mail\InformCleaner;
use App\Http\Requests\StoreBookingRequest;
use App\Http\Requests\UpdateBookingRequest;

class BookingController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $bookings = Booking::with('customer', 'cleaner', 'city')->paginate(env('PAGINATION_ONPAGE', 10));
        return view('admin.booking.index', compact('bookings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $cities = City::all();
        return view('admin.booking.create', compact('cities'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBookingRequest $request, Booking $booking) {
        $fromDate = date("Y-m-d H:i:s", strtotime(request('date')));
        $toDate = date("Y-m-d H:i:s", strtotime(request('date') . ' ' . ' + ' . request('duration') . 'hours'));
        $freeCleaner = $booking->getFreeCleaners($fromDate, $toDate, request('city_id'));

        if ($freeCleaner) {
            //Check customer
            //If exist - update
            //If not exist - create
            $customer = Customer::where('email', request('email'))->first();
            if ($customer) {
                Customer::find($customer->id)->update([
                    'first_name' => request('first_name'),
                    'last_name' => request('last_name'),
                    'phone' => request('phone')
                ]);
                $customerId = $customer->id;
            } else {
                $customerId = Customer::create([
                            'first_name' => request('first_name'),
                            'last_name' => request('last_name'),
                            'email' => strtolower(request('email')),
                            'phone' => request('phone')
                        ])->id;
            }

            Booking::create([
                'customer_id' => $customerId,
                'cleaner_id' => $freeCleaner->id,
                'city_id' => request('city_id'),
                'date_from' => $fromDate,
                'date_to' => $toDate
            ]);

            $bookingInfo = [
                'date' => date('d-m-Y', strtotime(request('date'))),
                'time' => date('H:i', strtotime(request('date'))),
                'duration' => request('duration') . ' ' . (request('duration') > 1 ? 'Hours' : 'Hour'),
                'city' => City::find(request('city_id'))->first()->name,
                'name' => $freeCleaner->first_name . ' ' . $freeCleaner->last_name,
                'quality_score' => $freeCleaner->quality_score
            ];

            //Send mail
            \Mail::to(request('email'))->send(new CustomerBookingInfo($bookingInfo));
            \Mail::to($freeCleaner->email)->send(new InformCleaner($bookingInfo, $request));

            session()->flash('message-success', 'Booking was created');
            return redirect()->route('booking.index');
        } else {
            session()->flash('message-failure', 'Free cleaner not found. Try to choose another time.');
            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function show(Booking $booking) {
        return view('admin.booking.show', compact('booking'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function edit(Booking $booking) {
        $cities = City::all();
        $cleaners = Cleaner::all();
        $customers = Customer::all();
        return view('admin.booking.edit', compact('booking', 'cities', 'cleaners', 'customers'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateBookingRequest $request, Booking $booking) {
        //Check - if cleaner or city changed
        if ($booking->city_id != $request->city_id || $booking->cleaner_id != $request->cleaner_id) {
            $cleaner = City::find($request->city_id)->cleaners()->where('cleaners.id', $request->cleaner_id)->first();

            if (!$cleaner) {
                session()->flash('message-failure', 'This cleaner does not work in this city.');
                return redirect()->back()->withInput();
            }
        }
        $fromDate = date("Y-m-d H:i:s", strtotime($request->date));
        $toDate = date("Y-m-d H:i:s", strtotime($request->date . ' ' . ' + ' . $request->duration . 'hours'));
        $cleaner = $booking->getCleanerBookings($fromDate, $toDate, $request->cleaner_id);
        if ($cleaner->isNotEmpty()) {
            session()->flash('message-failure', 'This cleaner booked at this time.');
            return redirect()->back()->withInput();
        } else {
            $booking->update([
                'customer_id' => $request->customer_id,
                'cleaner_id' => $request->cleaner_id,
                'city_id' => $request->city_id,
                'date_from' => $fromDate,
                'date_to' => $toDate
            ]);
            session()->flash('message-success', 'Booking was updated.');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Booking  $booking
     * @return \Illuminate\Http\Response
     */
    public function destroy(Booking $booking) {
        $booking->delete();
        session()->flash('message-success', 'Booking was removed');
        return redirect()->route('booking.index');
    }

}

app/Http/Controllers/BookingController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Booking;
use App\Customer;
use App\City;
use App\Mail\CustomerBookingInfo;
use App\Mail\InformCleaner;
use App\Http\Requests\StoreBookingRequest;

class BookingController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $cities = City::orderBy('name')->get();
        return view('booking.index', compact('cities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreBookingRequest $request, Booking $booking) {
        $this->validate($request, [
            'date' => 'required|date|after:yesturday',
            //'time' => 'required|date_format:"H:i"',
            'duration' => 'required|integer|min:1|max:8',
            'city_id' => 'required|integer|exists:cities,id',
            'first_name' => 'required|min:2|max:100',
            'last_name' => 'required|min:2|max:100',
            'email' => 'required|email',
            'phone' => 'nullable|regex:#^\s*((\+?\s*(\(\s*)?3)?[\s-]*(\(\s*)?8[\s-]*)?(\(\s*)?0[\s-\(]*[1-9][\s-]*\d(\s*\))?([\s-]*\d){7}\s*$#'
        ]);
        
        $fromDate = date("Y-m-d H:i:s", strtotime(request('date')));
        $toDate = date("Y-m-d H:i:s", strtotime(request('date') . ' ' . ' + ' . request('duration') . 'hours'));
        $freeCleaner = $booking->getFreeCleaners($fromDate, $toDate, request('city_id'));

        if ($freeCleaner) {
            //Check customer
            //If exist - update
            //If not exist - create
            $customer = Customer::where('email', request('email'))->first();
            if ($customer) {
                Customer::find($customer->id)->update([
                    'first_name' => request('first_name'),
                    'last_name' => request('last_name'),
                    'phone' => request('phone')
                ]);
                $customerId = $customer->id;
            } else {
                $customerId = Customer::create([
                            'first_name' => request('first_name'),
                            'last_name' => request('last_name'),
                            'email' => strtolower(request('email')),
                            'phone' => request('phone')
                        ])->id;
            }

            Booking::create([
                'customer_id' => $customerId,
                'cleaner_id' => $freeCleaner->id,
                'city_id' => request('city_id'),
                'date_from' => $fromDate,
                'date_to' => $toDate
            ]);

            $bookingInfo = [
                'date' => date('d-m-Y', strtotime(request('date'))),
                'time' => date('H:i', strtotime(request('date'))),
                'duration' => request('duration') . ' ' . (request('duration') > 1 ? 'Hours' : 'Hour'),
                'city' => City::find(request('city_id'))->name,
                'name' => $freeCleaner->first_name . ' ' . $freeCleaner->last_name,
                'quality_score' => $freeCleaner->quality_score
            ];

            //Send mail
            \Mail::to(request('email'))->send(new CustomerBookingInfo($bookingInfo));
            \Mail::to($freeCleaner->email)->send(new InformCleaner($bookingInfo, $request));

            //return view('booking.success', compact('freeCleaner', 'request'));
            return redirect('/booking/success')->with($bookingInfo);
        } else {
            session()->flash('message-failure', 'Free cleaner not found. Try to choose another time.');
            //return view('booking.failure', compact('freeCleaner', 'request', 'cities'));
            return redirect('/booking/failure')->withInput()->with('error-key', true);
        }


        //return view('booking.create', compact('freeCleaner', 'request'));
    }

    public function success() {
        if (session()->has('date') && session()->has('quality_score')) {
            return view('booking.success');
        } else {
            return redirect('/');
        }
    }

    public function failure() {
        if (session()->has('error-key')) {
            $cities = City::all();
            return view('booking.failure', compact('cities'));
        } else {
            return redirect('/');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show() {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }

}

resources/views/admin/booking/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Booking add</div>
                <div class="panel-body">
                    <form name="bookit-index" id="bookit-index" method="POST" action="{{ route('booking.store') }}">
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group{{ $errors->has('date') ? ' has-error' : '' }}">
                                    <label for="date">Date and time</label>
                                    <div class="input-group date" id="datepicker-date-index">
                                        <input type="datetime" class="form-control" name="date" id="date" placeholder="dd-mm-yyyy">
                                        <span class="input-group-addon">
                                            <span class="glyphicon glyphicon-calendar"></span>
                                        </span>
                                    </div>
                                    @if ($errors->has('date'))
                                    <span class="help-block has-error">
                                        <strong>{{ $errors->first('date') }}</strong>
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('duration') ? ' has-error' : '' }}">
                                    <label for="duration">Duration</label>
                                    @include('partials.booking.duration_select', ['duration' => old('duration'), 'durationMax' => 8])
                                    @if ($errors->has('duration'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('duration') }}</strong>
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('city_id') ? ' has-error' : '' }}">
                                    <label for="city">City</label>
                                    <select class="form-control" name="city_id" id="city">
                                        @foreach ($cities as $city)
                                        <option value="{{$city->id}}">{{$city->name}}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('city_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('city_id') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group{{ $errors->has('first_name') ? ' has-error' : '' }}">
                                    <label for="first_name">First name</label>
                                    <input type="text" class="form-control" name="first_name" id="first_name" placeholder="First name" value="{{old('first_name')}}" required>
                                    @if ($errors->has('first_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('first_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('last_name') ? ' has-error' : '' }}">
                                    <label for="last_name">Last name</label>
                                    <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Last name" value="{{old('last_name')}}" required>
                                    @if ($errors->has('last_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('last_name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                                    <label for="email">E-mail</label>
                                    <input type="email" class="form-control" name="email" id="email" placeholder="mail@address.com" value="{{old('email')}}" required>
                                    @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
                                    <label for="phone">Phone <small>(optional)</small></label>
                                    <input type="tel" class="form-control" name="phone" id="phone" placeholder="(067) 123-45-67" value="{{old('phone')}}">
                                    @if ($errors->has('phone'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('phone') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="text-center">
                            <button type="submit" class="btn btn-lg btn-green">Book now</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/booking/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Bookings</div>
                <div class="panel-body">
                    @if ($bookings->isNotEmpty())
                    <table class="table table-bordered">
                        <tr>
                            <td>ID</td>
                            <td>Customer Name</td>
                            <td>Customer phone</td>
                            <td>Customer e-mail</td>
                            <td>Cleaner name</td>
                            <td>City</td>
                            <td>Date from</td>
                            <td>Date to</td>
                            <td></td>
                        </tr>
                        @foreach($bookings as $booking)
                        <tr>
                            <td><a href="{{ route('booking.show', ['id' => $booking->id]) }}">{{ $booking->id }}</a></td>
                            <td><a href="{{ route('customer.show', ['id' => $booking->customer->id]) }}">{{ $booking->customer->first_name }} {{ $booking->customer->last_name }}</a></td>
                            <td>{{ $booking->customer->phone }}</td>
                            <td>{{ $booking->customer->email }}</td>
                            <td><a href="{{ route('cleaner.show', ['id' => $booking->cleaner->id]) }}">{{ $booking->cleaner->first_name }} {{ $booking->cleaner->last_name }}</a></td>
                            <td><a href="{{ route('city.show', ['id' => $booking->city->id]) }}">{{ $booking->city->name }}</a></td>
                            <td>{{ $booking->date_from }}</td>
                            <td>{{ $booking->date_to }}</td>
                            <td class="text-right">
                                <form action="{{ route('booking.destroy', ['id' => $booking->id]) }}" method="POST">
                                    <div class="btn-group-xs" role="group" aria-label="...">
                                        <a href="{{ route('booking.edit', ['id' => $booking->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-danger">
                                            <span class="glyphicon glyphicon-trash"></span> Remove
                                        </button>
                                    </div>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </table>
                    @else
                    <div class="alert alert-danger" role="alert">No booking defined</div>
                    @endif
                    <div class="text-center">
                        <a class="btn btn-default" href="{{ route('booking.create') }}">Add booking</a>
                    </div>
                </div>
                <div class="text-center">{{ $bookings->links() }}</div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/booking/show.blade.php
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Booking</div>
                <div class="panel-body">
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>Date from:</strong>
                        </div>
                        <div class="col-md-6">
                            {{ $booking->date_from }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>Date to:</strong>
                        </div>
                        <div class="col-md-6">
                            {{ $booking->date_to }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>Customer name:</strong>
                        </div>
                        <div class="col-md-6">
                            <a href="{{ route('customer.show', ['id' => $booking->customer->id]) }}">
                                {{ $booking->customer->first_name }} {{ $booking->customer->last_name }}
                            </a>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>Customer phone:</strong>
                        </div>
                        <div class="col-md-6">
                            {{ $booking->customer->phone }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>Customer e-mail:</strong>
                        </div>
                        <div class="col-md-6">
                            {{ $booking->customer->email }}
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>Cleaner name:</strong>
                        </div>
                        <div class="col-md-6">
                            <a href="{{ route('cleaner.show', ['id' => $booking->cleaner->id]) }}">
                                {{ $booking->cleaner->first_name }} {{ $booking->cleaner->last_name }}
                            </a>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6 text-right">
                            <strong>City:</strong>
                        </div>
                        <div class="col-md-6">
                            <a href="{{ route('city.show', ['id' => $booking->city->id]) }}">
                                {{ $booking->city->name }}
                            </a>
                        </div>
                    </div>
                    <div class="form-group text-center">
                        <form action="{{ route('booking.destroy', ['id' => $booking->id]) }}" method="POST">
                            <div class="btn-group" role="group" aria-label="...">
                                <a href="{{ route('booking.edit', ['id' => $booking->id]) }}" class="btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a>
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <button type="submit" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"></span> Remove
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
@endsection